
package org.fcuan.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StationServer", targetNamespace = "http://service.ws.fcuan.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StationServer {


    /**
     * 
     * @param name
     * @return
     *     returns org.fcuan.ws.service.Estacao
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterInfoEstacao", targetNamespace = "http://service.ws.fcuan.org/", className = "org.fcuan.ws.service.ObterInfoEstacao")
    @ResponseWrapper(localName = "obterInfoEstacaoResponse", targetNamespace = "http://service.ws.fcuan.org/", className = "org.fcuan.ws.service.ObterInfoEstacaoResponse")
    @Action(input = "http://service.ws.fcuan.org/StationServer/obterInfoEstacaoRequest", output = "http://service.ws.fcuan.org/StationServer/obterInfoEstacaoResponse")
    public Estacao obterInfoEstacao(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param email
     * @param stationId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "levantarBicicleta", targetNamespace = "http://service.ws.fcuan.org/", className = "org.fcuan.ws.service.LevantarBicicleta")
    @ResponseWrapper(localName = "levantarBicicletaResponse", targetNamespace = "http://service.ws.fcuan.org/", className = "org.fcuan.ws.service.LevantarBicicletaResponse")
    @Action(input = "http://service.ws.fcuan.org/StationServer/levantarBicicletaRequest", output = "http://service.ws.fcuan.org/StationServer/levantarBicicletaResponse")
    public int levantarBicicleta(
        @WebParam(name = "station_id", targetNamespace = "")
        String stationId,
        @WebParam(name = "email", targetNamespace = "")
        String email);

    /**
     * 
     * @param email
     * @param stationId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "entregarBicicleta", targetNamespace = "http://service.ws.fcuan.org/", className = "org.fcuan.ws.service.EntregarBicicleta")
    @ResponseWrapper(localName = "entregarBicicletaResponse", targetNamespace = "http://service.ws.fcuan.org/", className = "org.fcuan.ws.service.EntregarBicicletaResponse")
    @Action(input = "http://service.ws.fcuan.org/StationServer/entregarBicicletaRequest", output = "http://service.ws.fcuan.org/StationServer/entregarBicicletaResponse")
    public int entregarBicicleta(
        @WebParam(name = "station_id", targetNamespace = "")
        String stationId,
        @WebParam(name = "email", targetNamespace = "")
        String email);

}
